### ISSUE TITLE
multiple RMD in one Repo

### ISSUE THREAD

**Issue by brieaspasia** [brieaspasia/mp-diagnostics#2]
I understand how to commit/push/pull/clone one RMD in a repo, but I still don't understand how it works with multiple RMD that I'm creating for each graphic.  I keep getting an error message that mp-diagnostics is not an empty repo and I can't add a different RMD

**Comment by itchyshin** [comment]
Did you name they different? Send me the file which you wnat me to upload for the repo

**Comment by mlagisz** [comment]
Brie, maybe you are trying to add a new project?
You should be able to have multiple Rmd files within a project.
For now, if you cannot do this form inside RStudio, is to drag and drop your file into GitHub window in web browser (via Code tab -> Add File -> upload) - this always works. Then you need to pull all files into RStudio.

**Comment by itchyshin** [comment]
Hope Losia sorted this out - I only have time in the afternoon to go to do
some Github stuff - will get there eventually

**Comment by itchyshin** [comment]
@brieaspasia I have uploaded it via RStudio (via file in my computer) - read what @mlagisz wrote above
